[MPLUGIN-104] Fixing NoSuchMethodError in AbstractMavenReport...resulting from changed in the Renderer interface from doxia-site-renderer-1.0-alpha-7. Updating doxia deps to use -alpha-10 now.
git-svn-id: https://svn.apache.org/repos/asf/maven/shared/branches/maven-reporting-impl-2.0.4.1-dev@639776 13f79535-47bb-0310-9956-ffa450edef68