Simplify code, also required since M3.0 throws java.lang.NoSuchMethodError: org.codehaus.plexus.PlexusContainer.hasComponent(Ljava/lang/String;Ljava/lang/String;)Z
git-svn-id: https://svn.apache.org/repos/asf/maven/shared/trunk@1682606 13f79535-47bb-0310-9956-ffa450edef68